### ISSUE TITLE
embeddings_mask datatype

### ISSUE THREAD

**Issue by tongcu** [tatp22/linformer-pytorch#14]
Is embeddings_mask a bool variable in your data？

**Comment by tatp22** [comment]
Hi @tongcu!

The `embeddings_mask` is supposed to be a `torch.BoolTensor` type. Basically, it is a torch tensor that is filled with boolean values, and the inputs that are `False` are the ones that are masked out.

The way it works is that it is the same length as the input, except that on the input size dimension, it is supposed to be filled with booleans instead of embedding tokens (in the case of the of the `LinformerLM` module) or vectors (for `Linformer`).
