### ISSUE TITLE
Error when using method="no_params" and GPU, because E and F incorrectly remain on CPU

### ISSUE THREAD

**Issue by RaivoKoot** [tatp22/linformer-pytorch#20]
When you create a Linformer() with `method="no_params"` and then load the model on your cuda device, you will get an error when trying to use the model. This is because the E and F matrices in the model **accidentally** remain on the CPU. When you call forward with an input, you will get an error at some point because the attention heads are trying to multiply the E matrix on CPU with another matrix on the GPU.

Basically, when you call Linformer().cuda() under this situation, the E and F matrices are not moved to the GPU.
(From what I've read so far, in order for them to be put on the GPU with a `cuda()` call, you also need to assign E to self.E in Linformer. However, this still doesn't fix it because of the lambdas in your Linformer initializer I think. The `cuda()` call can't track down the E and F inside the MHAttention objects inside the lambda call it seems)

My temporary fix is changing `E_proj = get_EF(input_size, dim_k, method, head_dim)` in the `__init__` of Linformer to `E_proj = get_EF(input_size, dim_k, method, head_dim).cuda()`, but I think this would give an error if you do not have a gpu installed.

**Comment by tatp22** [comment]
Hi @RaivoKoot!

I think the issue is simple to fix. I think all that we need to do is, in the forward call, we need to add a `self.E = self.E.to(K.device)` between these two lines

https://github.com/tatp22/linformer-pytorch/blob/0fe2c6206ac5a6a44cedb7fe97b773dad1320c47/linformer_pytorch/linformer_pytorch.py#L157-L158

And we need to add a `self.F = self.F.to(V.device)` between these two lines:

https://github.com/tatp22/linformer-pytorch/blob/0fe2c6206ac5a6a44cedb7fe97b773dad1320c47/linformer_pytorch/linformer_pytorch.py#L177-L178

I'll make a new pull request right quick, I think this should fix it.

**Comment by tatp22** [comment]
Just made it, let me know if it works for you. If it does I'll pull it in and up the version to `0.19.3`. It works for me, but I wanna know if it fixes your bug.

**Comment by tatp22** [comment]
I merged this in, hopefully it works for your case as well

**Comment by RaivoKoot** [comment]
Works like a charm (1 GPU)! Thanks. Great work on the library btw! Will test everything out in a multi GPU setting as well!
